### PR TITLE
Added the health status from healthcheck to RuntimeContainer struct

### PR DESCRIPTION
**Pull request by free6k**
Added right work for containers with enabled healthchecks

Now can know and work with Health Status in the container state

### CODE REVIEW

**Comment by buchdag** [comment]
Hi @free6k 

What happen for containers that do not have a healhcheck ?

**Comment by free6k** [comment]
@buchdag Nothing, will work as worked before this or, if you will add healthcheck, then it check status

**Comment by buchdag** [comment]
@free6k I don't know what happened to your branch but would you try to cleanup the commit history so this can be reviewed ?

**Comment by free6k** [comment]
@buchdag done

**Comment by inyerade** [comment]
Hi, any intention on merge this?

**Comment by smax17** [comment]
It would be great to merge this. Feature is really desired!

**Review by buchdag — APPROVED** [review]

**Pull request merged**
